### ISSUE TITLE
[Feature] Make this a download manager?

### ISSUE THREAD

**Issue by dishb** [Akascape/tkinter-toolkit#2]
I saw that the README said that this app was _not_ a download manager. But why not make it one?

For the libraries that are installable via `pip`, you could add a button to their pages allowing you to install them.

The idea would be something like this:
1. User clicks button
2. The button has a command binded to the first (left) button
3. Upon clicking, through the `subprocess` module, you can run `pip install <library>`

Since macOS and Windows use different commands, you can use `platform.system()` to check if it is a Windows, Linux, or macOS user. For Windows use `pip`, and for macOS and Linux use `pip3`.

**Comment by Akascape** [comment]
I know, but there are some manual packages which are not uploaded to pip.

**Comment by dishb** [comment]
For those manual packages you could simply, _not_ include a button for download, or have a button that takes you to the Github repository (or whatever other source).

This is just an idea - I understand the actual implementation will be harder.
