### ISSUE TITLE
@Akascape I need ur help ( pleaseee )

### ISSUE THREAD

**Issue by Assia55** [Akascape/tkinter-toolkit#20]
I've spent the past year developing a **comprehensive app**, including both the **back-end** and **front-end**. For the **front-end**, I've used `CustomTkinter` to create multiple pages such as login, home, and settings...
A significant amount of time went into designing and programming **the front-end**.

Currently, I’m facing an issue that I real a need your help ( @Akascape ) . 
I am sure I will consider your reply as a firm decision .

Every page has packing many widgets , I have searched and confirmed that this is a problem of `tkinter` not `customtkinter`,

That's why I got the idea for the solution. i will `place` one frame with lable has "loading ..." than i will `pack` all widgets behind loading frame after all widgets ( pack ) i will remove loading freme using `app.after()`

I tried, but I didn't succeed, so I am asking for your help. ( please )

**Comment by Assia55** [comment]
I’m sure your guidance will be instrumental in resolving this problem @Akascape .

**Comment by Assia55** [comment]
i want create smooth movement between pages, by adding loading frame between pages, to solve `performance issues when packing many widgets`

**Comment by Akascape** [comment]
@Assia55 You can use place method for the loading page so that it overlaps without any geometry issue. Then you can use `.place_forget()` method to remove it.
Example:
```python
# switch from Page 1 to Page 2
Page_1.forget() 
Loading_page.place(x=0,y=0)
Page_2.pack(expand=True, fill="both")
Loading_page.place_forget()
```
